name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 100.93.83.43
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /srv/shopdemo
            git pull
            npm install
            pm2 restart all
