name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.VPN_KETNOISSH }}

      - name: Check Tailscale
        run: |
          tailscale status
          ping -c 4 100.93.83.43

      - name: Setup SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.PASS }}" \
          ssh \
          -p 22 \
          -o StrictHostKeyChecking=no \
          -o PreferredAuthentications=password \
          -o PubkeyAuthentication=no \
          root@100.93.83.43 << 'EOF'

          set -e

          echo "===== START ====="

          hostname
          whoami

          cd /srv/shopdemo

          echo "===== GIT PULL ====="
          git pull origin master

          echo "===== NPM INSTALL ====="
          npm install --production

          echo "===== PM2 RESTART ====="
          pm2 restart shopdemo || pm2 start server.js --name shopdemo

          echo "===== PM2 SAVE ====="
          pm2 save

          echo "===== DONE ====="

          EOF
